name             'mule'
maintainer       'ShopKeep DevOps'
maintainer_email 'devops@shopkeep.com'
license          'All rights reserved'
description      'Installs/Configures mule'
long_description 'Installs/Configures mule'
version          '0.1.3'

depends 'apt', '~> 2.6.0'
depends 'archive', '~> 0.2.6'
depends 'java', '~> 1.28.0'
depends 'yum', '~> 3.3.2'
